force-app/main/default/objects/TV_Series__c/TV_Series__c.object-meta.xml
<CustomObject>
    <label>TV Series</label>
    <nameField>
        <label>TVSeries Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TV Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TV_Series__c/fields/Age_rating__c.field-meta.xml
<CustomField>
    <fullName>Age_rating__c</fullName>
    <label>Age rating</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No age restriction</fullName>
            </value>
            <value>
                <fullName>7+</fullName>
            </value>
            <value>
                <fullName>13+</fullName>
            </value>
            <value>
                <fullName>18+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TV_Series_Episode__c/TV_Series_Episode__c.object-meta.xml
<CustomObject>
    <label>TV Series Episode</label>
    <nameField>
        <label>TV Series Episode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TV Series Episodes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TV_Series_Episode__c/fields/TV_Series__c.field-meta.xml
<CustomField>
    <fullName>TV_Series__c</fullName>
    <label>TV Series</label>
    <referenceTo>TV_Series__c</referenceTo>
    <relationshipLabel>TV Series Episodes</relationshipLabel>
    <relationshipName>TV_Series_Episodes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TV_Series_Episode__c/fields/TV_Series_Season__c.field-meta.xml
<CustomField>
    <fullName>TV_Series_Season__c</fullName>
    <label>TV Series Season</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>TV_Series_Season__c.TVSeries__c</field>
            <operation>equals</operation>
            <valueField>$Source.TV_Series__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>TV_Series_Season__c</referenceTo>
    <relationshipLabel>TV Series Episodes</relationshipLabel>
    <relationshipName>TV_Series_Episodes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TV_Series_Season__c/TV_Series_Season__c.object-meta.xml
<CustomObject>
    <label>TV Series Season</label>
    <nameField>
        <label>TV Series Season</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TV Series Seasons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TV_Series_Season__c/fields/TVSeries__c.field-meta.xml
<CustomField>
    <fullName>TVSeries__c</fullName>
    <label>TVSeries</label>
    <referenceTo>TV_Series__c</referenceTo>
    <relationshipLabel>TV Series Seasons</relationshipLabel>
    <relationshipName>TV_Series_Seasons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TVSeries__c/TVSeries__c.object-meta.xml
<CustomObject>
    <label>TVSeries</label>
    <nameField>
        <label>TVSeries Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TVSeries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EpisodesGenerator.cls
public with sharing class EpisodesGenerator {

    public static void generateSeriesData(String seriesName, String ageRating, Integer numEpisodes) {
        TV_Series__c newSeries = new TV_Series__c(
            Name = seriesName,
            Age_rating__c = ageRating
        );

        insert newSeries;

        TV_Series_Season__c newSeason = new TV_Series_Season__c(
            TVSeries__c = newSeries.Id,
            Name = seriesName + ' S1'
        );

        insert newSeason;

        List<TV_Series_Episode__c> episodes = new List<TV_Series_Episode__c>();
        
        for (Integer i = 1; i <= numEpisodes; i++) {
            TV_Series_Episode__c episode = new TV_Series_Episode__c(
                Name = seriesName + ' S1' + ' E' + i,
                TV_Series_Season__c = newSeason.Id,
                TV_Series__c = newSeries.Id
            );
            episodes.add(episode);
        }

        insert episodes;
    }

    public static void generateSeriesDataWithProperEpisodeNameFormat(Integer numEpisodes) {
        TV_Series__c newSeries = new TV_Series__c(
            Name = 'The Bald and the Beautiful',
            Age_rating__c = '7+'
        );

        insert newSeries;

        TV_Series_Season__c newSeason = new TV_Series_Season__c(
            TVSeries__c = newSeries.Id,
            Name = 'TB&TB S01'
        );

        insert newSeason;

        List<TV_Series_Episode__c> episodes = new List<TV_Series_Episode__c>();
        
        for (Integer i = 1; i <= numEpisodes; i++) {
            if (i<10){
                TV_Series_Episode__c episode = new TV_Series_Episode__c(
                    Name = 'E000' + i + ' S1' + ' TB&TB',
                    TV_Series_Season__c = newSeason.Id,
                    TV_Series__c = newSeries.Id
                );
                episodes.add(episode);

            } else if (i<100){
                TV_Series_Episode__c episode = new TV_Series_Episode__c(
                    Name = 'E00' + i + ' S1' + ' TB&TB',
                    TV_Series_Season__c = newSeason.Id,
                    TV_Series__c = newSeries.Id
                );
                episodes.add(episode);

            } else if (i<1000){
                TV_Series_Episode__c episode = new TV_Series_Episode__c(
                    Name = 'E0' + i + ' S1' + ' TB&TB',
                    TV_Series_Season__c = newSeason.Id,
                    TV_Series__c = newSeries.Id
                );
                episodes.add(episode);

            } else {
                TV_Series_Episode__c episode = new TV_Series_Episode__c(
                    Name = 'E' + i + ' S1' + ' TB&TB',
                    TV_Series_Season__c = newSeason.Id,
                    TV_Series__c = newSeries.Id
                );
                episodes.add(episode);

            }
        }

        insert episodes;
    }

}