force-app/main/default/objects/TV_Series__c/TV_Series__c.object-meta.xml
<CustomObject>
    <label>TV Series</label>
    <nameField>
        <label>TVSeries Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TV Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TV_Series__c/fields/Age_rating__c.field-meta.xml
<CustomField>
    <fullName>Age_rating__c</fullName>
    <label>Age rating</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No age restriction</fullName>
            </value>
            <value>
                <fullName>7+</fullName>
            </value>
            <value>
                <fullName>13+</fullName>
            </value>
            <value>
                <fullName>18+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TV_Series__c/fields/No_of_episodes__c.field-meta.xml
<CustomField>
    <fullName>No_of_episodes__c</fullName>
    <label>No of episodes</label>
    <summaryForeignKey>TV_Series_Episode__c.TV_Series__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/TV_Series__c/fields/No_of_seasons__c.field-meta.xml
<CustomField>
    <fullName>No_of_seasons__c</fullName>
    <label>No of seasons</label>
    <summaryForeignKey>TV_Series_Season__c.TVSeries__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/TV_Series__c/fields/TV_Series_Story__c.field-meta.xml
<CustomField>
    <fullName>TV_Series_Story__c</fullName>
    <label>TV Series Story</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TV_Series__c/fields/TVSeries_Logo__c.field-meta.xml
<CustomField>
    <fullName>TVSeries_Logo__c</fullName>
    <label>TV Series Logo</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/TV_Series_Episode__c/TV_Series_Episode__c.object-meta.xml
<CustomObject>
    <label>TV Series Episode</label>
    <nameField>
        <label>TV Series Episode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TV Series Episodes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TV_Series_Episode__c/fields/Episode_Story__c.field-meta.xml
<CustomField>
    <fullName>Episode_Story__c</fullName>
    <label>Episode Story</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TV_Series_Episode__c/fields/TV_Series__c.field-meta.xml
<CustomField>
    <fullName>TV_Series__c</fullName>
    <label>TV Series</label>
    <referenceTo>TV_Series__c</referenceTo>
    <relationshipLabel>TV Series Episodes</relationshipLabel>
    <relationshipName>TV_Series_Episodes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TV_Series_Episode__c/fields/TV_Series_Season__c.field-meta.xml
<CustomField>
    <fullName>TV_Series_Season__c</fullName>
    <label>TV Series Season</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>TV_Series_Season__c.TVSeries__c</field>
            <operation>equals</operation>
            <valueField>$Source.TV_Series__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>TV_Series_Season__c</referenceTo>
    <relationshipLabel>TV Series Episodes</relationshipLabel>
    <relationshipName>TV_Series_Episodes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TV_Series_Season__c/TV_Series_Season__c.object-meta.xml
<CustomObject>
    <label>TV Series Season</label>
    <nameField>
        <label>TV Series Season</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TV Series Seasons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TV_Series_Season__c/fields/No_of_episodes__c.field-meta.xml
<CustomField>
    <fullName>No_of_episodes__c</fullName>
    <label>No of episodes</label>
    <summaryForeignKey>TV_Series_Episode__c.TV_Series_Season__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/TV_Series_Season__c/fields/TVSeries__c.field-meta.xml
<CustomField>
    <fullName>TVSeries__c</fullName>
    <label>TVSeries</label>
    <referenceTo>TV_Series__c</referenceTo>
    <relationshipLabel>TV Series Seasons</relationshipLabel>
    <relationshipName>TV_Series_Seasons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TVSeries__c/TVSeries__c.object-meta.xml
<CustomObject>
    <label>TVSeries</label>
    <nameField>
        <label>TVSeries Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TVSeries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DataCollector.cls
public with sharing class DataCollector {

    /**
    * @date 02.08.2022
    * @Description Public method used to get list of all TV Series stored in database
    * @return a list of all records stored in "TV_Series__c" sObject
    * @return fields included (api names): Id, Name, No_of_seasons__c, No_of_episodes__c, Age_rating__c, TV_Series_Story__c, TVSeries_Logo__c
    */
    @AuraEnabled
    public static List<TV_Series__c> getSeries(){
        
        List<TV_Series__c> ownerRecords = [SELECT Id, Name, No_of_seasons__c, No_of_episodes__c, Age_rating__c, TV_Series_Story__c, TVSeries_Logo__c
                                            FROM TV_Series__c];

        if(ownerRecords.Size() > 0) {
            return ownerRecords;  
          } 
          else {
              return null;
          }
    }

    /**
    * @date 02.08.2022
    * @Description Public method used to get list of all seasons for TV Series Id passed as parameter
    * @param outSeries (String type) Id value of TV Series selected
    * @return a list of child records related to selected TV Series stored in "TV_Series_Season__c" sObject
    * @return fields included (api names): Id, Name, No_of_episodes__c
    */

    @AuraEnabled
    public static List<TV_Series_Season__c> getSeasons(String outSeries) {

        if(isAllowedIdType(outSeries, 'TV_Series__c')) {
            List<TV_Series_Season__c> seasons = [SELECT Id, Name, No_of_episodes__c
                                            FROM TV_Series_Season__c
                                            WHERE TVSeries__c =: outSeries]; 

            if(seasons.Size() > 0) {
                return seasons;  
            } else {
                return null;
            }
        } else {
            return null;
        }
    }

    /**
    * @date 02.08.2022
    * @Description Public method used to get list of all episodes of the selected season of the selected TV Series stored in database
    * @param outSeason (String type) Id value for selected season of earlier selected series
    * @return a list of child records related to selected season stored in "TV_Series_Episode__c" sObject
    * @return field included (api names): Id, Name, Episode_Story__c
    */

    @AuraEnabled
    public static List<TV_Series_Episode__c> getEpisodes(String outSeason){

        if(isAllowedIdType(outSeason, 'TV_Series_Season__c')) {
            List<TV_Series_Episode__c> episodes = [SELECT Id, Name, Episode_Story__c
                                FROM TV_Series_Episode__c
                                WHERE TV_Series_Season__c =: outSeason];

            if(episodes.Size() > 0) {
                return episodes;  
            } else {
                return null;
            }
        } else {
            return null;
        }
    }


    /**
    * @date 02.08.2022
    * @Description Private method used to validate presence and type of Id for each record in a list of records
    *        returned by parent method.
    * @param inputId field's api name contating Id value for an object
    * @param objectType object's api name
    * @return true or false
    */

    private static Boolean isAllowedIdType( String inputId, String objectType )
    {
        if ( !String.isBlank( inputId ) && inputId instanceof Id )
        {
            Id verifyId = Id.valueOf( inputId );
            if ( objectType.equalsIgnoreCase( verifyId.getSobjectType( ).getDescribe( ).getName( ) ) )
            {
                return true;
            }
        }
        return false;
    }

}