force-app/main/default/objects/TV_Series__c/TV_Series__c.object-meta.xml
<CustomObject>
    <label>TV Series</label>
    <nameField>
        <label>TVSeries Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TV Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TV_Series__c/fields/Age_rating__c.field-meta.xml
<CustomField>
    <fullName>Age_rating__c</fullName>
    <label>Age rating</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No age restriction</fullName>
            </value>
            <value>
                <fullName>7+</fullName>
            </value>
            <value>
                <fullName>13+</fullName>
            </value>
            <value>
                <fullName>18+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TV_Series_Episode__c/TV_Series_Episode__c.object-meta.xml
<CustomObject>
    <label>TV Series Episode</label>
    <nameField>
        <label>TV Series Episode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TV Series Episodes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TV_Series_Episode__c/fields/TV_Series__c.field-meta.xml
<CustomField>
    <fullName>TV_Series__c</fullName>
    <label>TV Series</label>
    <referenceTo>TV_Series__c</referenceTo>
    <relationshipLabel>TV Series Episodes</relationshipLabel>
    <relationshipName>TV_Series_Episodes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TV_Series_Episode__c/fields/TV_Series_Season__c.field-meta.xml
<CustomField>
    <fullName>TV_Series_Season__c</fullName>
    <label>TV Series Season</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>TV_Series_Season__c.TVSeries__c</field>
            <operation>equals</operation>
            <valueField>$Source.TV_Series__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>TV_Series_Season__c</referenceTo>
    <relationshipLabel>TV Series Episodes</relationshipLabel>
    <relationshipName>TV_Series_Episodes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TV_Series_Season__c/TV_Series_Season__c.object-meta.xml
<CustomObject>
    <label>TV Series Season</label>
    <nameField>
        <label>TV Series Season</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TV Series Seasons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TV_Series_Season__c/fields/TVSeries__c.field-meta.xml
<CustomField>
    <fullName>TVSeries__c</fullName>
    <label>TVSeries</label>
    <referenceTo>TV_Series__c</referenceTo>
    <relationshipLabel>TV Series Seasons</relationshipLabel>
    <relationshipName>TV_Series_Seasons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TVSeries__c/TVSeries__c.object-meta.xml
<CustomObject>
    <label>TVSeries</label>
    <nameField>
        <label>TVSeries Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TVSeries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DataCollectorTest.cls
@isTest
public with sharing class DataCollectorTest {

    /**
    * @date 04.08.2022
    * @Description positive case test method for DataCollector.getSeriesAndSeasons() responsible
        for delivery data to constructor for seasonSelector LWC
    */

    @isTest static void getSeriesAndSeasonsTest(){

        for (Integer i = 0; i < 3; i++) {
            TV_Series__c testSeriesRecord = new TV_Series__c(
                Name = 'TestSeries' + i,
                Age_rating__c = '13+',
                Series_Trailer__c = 'http://'
            );
            insert testSeriesRecord;

            for (Integer j = 0; j < 2; j++) {
                TV_Series_Season__c testSeasonRecord = new TV_Series_Season__c(
                    Name = 'TestSeason' + j,
                    TVSeries__c = testSeriesRecord.Id
                );
                insert testSeasonRecord;
            }
        }


        Test.startTest();
        List<TV_Series__c> returned = DataCollector.getSeriesAndSeasons();
        System.assertEquals(3, returned.size());
        Test.stopTest();
    }

    /**
    * @date 04.08.2022
    * @Description null return case  test method for DataCollector.getSeriesAndSeasons() responsible
        for delivery data to constructor for seasonSelector LWC
    */

    @isTest static void getSeriesAndSeasonsNullReturnTest(){

        Test.startTest();
        System.assertEquals(null, DataCollector.getSeriesAndSeasons());     
        Test.stopTest();   
    }

    /**
    * @date 04.08.2022
    * @Description positive case  test method for DataCollector.getEpisodesTest() responsible
        for delivery data to connectedCallback() method of episodeListDisplay LWC
    */

    @istest static void getEpisodesTest() {

        List<TV_Series_Episode__c> testEpisodeRecords = new List<TV_Series_Episode__c>();

        TV_Series__c testSeriesRecord = new TV_Series__c(
            Name = 'TestSeries',
            Age_rating__c = '13+',
            Series_Trailer__c = 'http://'
        );

        insert testSeriesRecord;

        TV_Series_Season__c testSeasonRecord = new TV_Series_Season__c(
            Name = 'TestSeason',
            TVSeries__c = testSeriesRecord.Id
        );

        insert testSeasonRecord;

        for (Integer i = 0; i < 5; i++) {
            TV_Series_Episode__c testEpisode = new TV_Series_Episode__c(
                Name = 'TestEpisode' + i,
                TV_Series__c = testSeriesRecord.Id,
                TV_Series_Season__c = testSeasonRecord.Id

            );

            testEpisodeRecords.add(testEpisode);   
        }

        insert testEpisodeRecords;

        Test.startTest();
        List<TV_Series_Episode__c> returned = DataCollector.getEpisodes(testSeasonRecord.Id);
        System.assertEquals(5, returned.size());
        Test.stopTest();
        
    }

    /**
    * @date 04.08.2022
    * @Description null return case  test method for DataCollector.getEpisodesTest() responsible
        for delivery data to connectedCallback() method of episodeListDisplay LWC
    */

    @istest static void getEpisodesNullReturnTest() {

        TV_Series__c testSeriesRecord = new TV_Series__c(
            Name = 'TestSeries',
            Age_rating__c = '13+',
            Series_Trailer__c = 'http://'
        );

        insert testSeriesRecord;

        TV_Series_Season__c testSeasonRecord = new TV_Series_Season__c(
            Name = 'TestSeason',
            TVSeries__c = testSeriesRecord.Id
        );

        insert testSeasonRecord;

        Test.startTest();
        System.assertEquals(null, DataCollector.getEpisodes(testSeasonRecord.Id));     
        System.assertEquals(null, DataCollector.getEpisodes('11111'));     
        Test.stopTest();  
    }

    /**
    * @date 04.08.2022
    * @Description negative case test method for DataMOdifier.isAllowedIdType(String inputId, String objectType) validator
            of paramter type
    */

    @isTest static void isAllowedIdTypeFaslseReturnTest(){

        Test.startTest();
        System.assertEquals(false, DataCollector.isAllowedIdType('1111', 'TV_Series_Season__c'));
        Test.stopTest();
    }
}